spring:
  datasource:
    name: testdb
    url: jdbc:h2:mem:testdb
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : none

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump,heapdump
  endpoint:
    health:
      show-details: always
    
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831
